### ISSUE TITLE
Cql client encryption is not working

### ISSUE THREAD

**Issue by irumman** [stargate/stargate#1001]
Hi,

I am trying to use stargate 1.0.25 in front of Cassandra 3.11 with enabling ssl for both server and client. Server ssl is working.
But client encryption is not working. 

```
env JAVA_OPTS='-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005 -Dstargate.unsafe.cassandra_config_path=/stargate/stargate/cass_configs/cassandra.yaml' \
./starctl --cluster-name cass \
--cluster-seed 10.10.10.21 \
--cluster-version 3.11 \
--listen 10.0.0.161 \
--dc cass \
--rack 3a \
--enable-auth

```

In cassandra.yaml, I have

```
client_encryption_options:
    enabled: true
    optional: true
    require_client_auth: true

```
In log, I can see:

`INFO  [main] 2021-06-08 15:11:05,959 Server.java:157 - Starting listening for CQL clients on /0.0.0.0:9042 (unencrypted)...`
    
Is there any other configuration that I should use to enable client ssl for cql?

Thanks.
