### ISSUE TITLE
Consistency with environment variables between Cassandra 3.11 and Stargate 3.11

### ISSUE THREAD

**Issue by clun** [stargate/stargate#1406]
I deployed an extended configuration in docker-compose: (work pretty well)
- 2 DC, 3 cassandra nodes in each DC
- 2 stargate nodes per DC

I noticed then the environment variables are not the same for a Cassandra node and a stargate node:

- A cassandra node `3.11`
```yaml
dc2n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9062:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1,dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
```

- A stargate node `3.11`
```
 dc2s1: 
    image: stargateio/stargate-3_11:v1.0.41
    depends_on: 
      - dc2n1
    networks:
      - backend
    ports:
      - 9053:9042
      - 8080:8080
      - 8081:8081
      - 8082:8082
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargatefull
      - CLUSTER_VERSION=3.11
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - ENABLE_AUTH=true
      #- CASSANDRA_RACK=rack1
      - RACK_NAME=rack1
      #- CASSANDRA_DC=DC2
      - DATACENTER_NAME=DC2
      #- CASSANDRA_SEEDS=dc1n1
      - SEED=dc2n1
```

Noticed in the end the discrepancies. I do not know if it would be considered a bug but worth mentionning.
