### ISSUE TITLE
Can not re-run failing V2 API tests due to eager ("always") Docker cleanup

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2163]
Sometimes one of Stargate V2 API test fails on CI; re-run for just that matrix job would usually be the way to do it.
Unfortunately clean up of Docker images in all cases (even failure):

```
  # runs always, deletes built docker image artifacts
  clean-up:
    name: Clean up
    runs-on: ubuntu-latest
    needs: int-tests
    if: ${{ always() }}
```

means that re-run attempt fails immediately. This can be fixed by only cleaning up Docker images on success.
But additionally it may be necessary to add some retention options to avoid possible accumulation of images on consistent failures.
