### ISSUE TITLE
scylladb stargate intigration problem problem

### ISSUE THREAD

**Issue by sanghanihimanshu** [stargate/stargate#2959]
this my compose file i only enable scylla.yaml

```authenticator: PasswordAuthenticator
authorizer: com.scylladb.auth.TransitionalAuthorizer
```
```yaml
version: '3.8'

services:
  scylla1:
    image: scylladb/scylla
    container_name: scylla-1
    networks:
      - cass-net
    volumes:
      - ./scylla.yaml:/etc/scylla/scylla.yaml
    environment:
      SCYLLA_CLUSTER_NAME: stargate-cluster

  stargate:
    image: stargateio/stargate-4_0:v1.0.57
    container_name: stargate
    networks:
      - cass-net
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "9042:9042"
    environment:
      CLUSTER_NAME: stargate-cluster
      CLUSTER_VERSION: 4.0
      SEED: scylla-1
      SIMPLE_SNITCH: 'true'
      ENABLE_AUTH: 'true'

networks:
  cass-net:
    driver: bridge
```
stargate can`t connect on port 7000 of scylladb
